apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: stsiyer/backend-app:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: JWT_SECRET
              value: "secret"
            - name: PORT
              value: "5000"
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MONGODB_URI
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 5000
      nodePort: 3000
